-- Migration: Create core tables for the flashcard system
-- Description: Creates the decks and flashcards tables with proper constraints and RLS enabled
-- Author: AI Assistant
-- Date: 2025-10-13

-- Create decks table
create table public.decks (
    id uuid primary key default gen_random_uuid(),
    user_id uuid not null references auth.users(id),
    name text not null check (name <> ''),
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Add comments to decks table and its columns
comment on table public.decks is 'Stores flashcard decks created by users';
comment on column public.decks.id is 'Unique identifier for the deck';
comment on column public.decks.user_id is 'Reference to the Supabase auth.users table';
comment on column public.decks.name is 'Name of the deck';
comment on column public.decks.description is 'Optional description of the deck';
comment on column public.decks.created_at is 'Timestamp when the deck was created';
comment on column public.decks.updated_at is 'Timestamp when the deck was last updated';

-- Enable RLS on decks table
alter table public.decks enable row level security;

-- Create flashcards table
create table public.flashcards (
    id uuid primary key default gen_random_uuid(),
    deck_id uuid not null references public.decks(id),
    user_id uuid not null references auth.users(id),
    front_content text not null check (front_content <> ''),
    back_content text not null check (back_content <> ''),
    status public.flashcard_status not null default 'new',
    ai_generated boolean not null default false,
    ai_accepted boolean,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

-- Add comments to flashcards table and its columns
comment on table public.flashcards is 'Stores individual flashcards belonging to decks';
comment on column public.flashcards.id is 'Unique identifier for the flashcard';
comment on column public.flashcards.deck_id is 'Reference to the deck this flashcard belongs to';
comment on column public.flashcards.user_id is 'Denormalized user_id for simplified RLS and performance';
comment on column public.flashcards.front_content is 'Content shown on the front of the flashcard';
comment on column public.flashcards.back_content is 'Content shown on the back of the flashcard';
comment on column public.flashcards.status is 'Current status in the spaced repetition system';
comment on column public.flashcards.ai_generated is 'Indicates if the flashcard was generated by AI';
comment on column public.flashcards.ai_accepted is 'Indicates if the AI-generated flashcard was accepted by the user';
comment on column public.flashcards.created_at is 'Timestamp when the flashcard was created';
comment on column public.flashcards.updated_at is 'Timestamp when the flashcard was last updated';

-- Enable RLS on flashcards table
alter table public.flashcards enable row level security;
